---
title: "Repository for EPSY 8264"
subtitle: "Fall 2025"
date: today
---




## Course Materials

<nav aria-label="materials">
- [Syllabus](https://docs.google.com/document/d/1EgJKuDkiIARgaHWutzh97DvgT9mlOwIwjMhZks1cngA/edit?usp=sharing)
- [Textbook: Matrix Algebra for Educational Scientists](https://zief0002.github.io/matrix-algebra/)
- [CSV Data Files (ZIP File)](https://github.com/zief0002/symmetrical-fiesta/raw/refs/heads/main/files/data.zip)
- [Data Dictionaries](https://docs.google.com/document/d/1NIIplixa8yFg-eLWqD246v-bAE5KYX8-99yZXXLRfw4/edit?usp=sharing)
- [R Scripts (ZIP File)](https://github.com/zief0002/symmetrical-fiesta/raw/refs/heads/main/files/R%20Scripts.zip)
</nav>

<br />


## Assignments

<nav aria-label="assignments">
<!-- - [Assignment 1: Matrix Algebra for Linear Regression](https://docs.google.com/document/d/1ZXfV635WEZ95Y1nICSLlMT_i5k1AyrrChE_pRQMKwGU/edit?usp=sharing) -->
<!-- - [Assignment 2: Path Analysis](https://docs.google.com/document/d/11EzuqiQZMmFzzonJ70YLru3qC7Wh80iCL7-JUmasdPA/edit?usp=sharing) -->
<!-- - [~~Assignment 3: Regression Diagnostics~~]() -->
<!-- - [Assignment 3: Using WLS to Model Data with Outliers](https://docs.google.com/document/d/1RDBLk8hB97CuG-hdj3I46Nwc2bQgeQSyI1dCIVTByl8/edit?usp=sharing) -->
<!-- - [Assignment 4: Collinearity and Dimension Reduction](https://docs.google.com/document/d/1Y1Bn3ynGod8jjQbMSCyLA8ypgOVKO4s41eExpDVYDX4/edit?usp=sharing) -->
<!-- - [Assignment 5: Ridge Regression](https://docs.google.com/document/d/1ZCRsM3VJPf_Ur5O52XVMAcPKIarqh99woxY2TuWpGBY/edit?usp=sharing) <span style="color: #ff2d21; font-size:13px;"> [<i>Updated 2025-10-24</i>]</span> -->
- Assignment 1: Matrix Algebra for Linear Regression [Closed]
- Assignment 2: Path Analysis [Closed]
- Assignment 3: Using WLS to Model Data with Outliers [Closed]
- Assignment 4: Collinearity and Dimension Reduction [Closed]
- Assignment 5: Ridge Regression [Closed]
- [Assignment 6: Cross Validation](https://docs.google.com/document/d/1qi2w9hGZ8kle4-Jri58cyjvR4-zdr8gob41nF2YtMNQ/edit?usp=sharing)
</nav>

<br />


## Notes

<nav aria-label="notes">
- **Regression Review**
  + [Notes](files/01-regression-review.pdf) | [Data](https://raw.githubusercontent.com/zief0002/fluffy-ants/main/data/pew.csv) | [Dictionary](https://zief0002.github.io/fluffy-ants/codebooks/pew.html) | [R Script file](scripts/00-01-regression-review.R)
- **Mathematical and Computational Foundations**
  + [Introduction to Matrix Algebra Worksheet](worksheets/01-introduction-to-matrix-algebra.html)
  + [Summation, Expectation, Variance, Covariance, and Correlation](notes/01-01-summation-expectation.html) 
  + [OLS Estimators and Their Properties](notes/01-02-ols-estimators-and-their-properties.html)
  + [Assumptions for OLS Regression and the Gauss-Markov Theorem](notes/01-03-assumptions-and-gauss-markov-theorem.html)
  + [Statistical Inference for the Regression Model](notes/01-04-statistical-inference-for-the-regression-model.html) 
  + [A Regression Example in Practice](notes/01-05-regression-example.html) 
- **Path Analysis**
  + [Regression From Summary Measures](notes/01-06-regression-from-summary-measures.html)
  + [Introduction to Path Analysis](notes/02-01-intro-to-path-analysis.html)
  + [Path Analysis Using R](notes/02-02-path-analysis-using-r.html)
- **Regression Diagnostics**
  + [Regression Diagnostics](notes/03-01-regression-diagnostics.html)
- **Tools for Dealing with Heteroskedasticity**
  + [Heteroskedasticity and Variance Stabilizing Transformations](notes/04-01-heteroskedasticity-and-transformations.html) <span style="color: #ff2d21; font-size:13px;"> [<i>Updated 2025-10-14</i>]</span>
    - [Background Reading: Log-Transformations in Regression](https://zief0002.github.io/adv-modeling/03-04-logarithmic-transformations-outcome.html)
    - [Background Reading: Likelihood and Log-Likelihood](https://zief0002.github.io/adv-modeling/02-03-likelihood-framework-for-evidence.html)
  + [Weighted Least Squares (WLS) and Sandwich Estimation](notes/04-02-wls-and-sandwich-estimation.html)
- **Diagnosing Collinearity and Tools for Dealing With It**
  + [Diagnosing Collinearity](notes/05-01-diagnosing-collinearity.html)
  + [Principal Components Analysis via Spectral Decomposition](notes/05-02-pca-via-spectral-decomposition.html)
  + [Principal Components Analysis via Singular Value Decomposition](notes/05-03-pca-via-svd.html)
    - [PCA Examples Script File](https://github.com/zief0002/symmetrical-fiesta/raw/main/scripts/pca-examples.R) <span style="color: #ff2d21; font-size:13px;"> [<i>Added 2025-11-12</i>]</span>
  + [Biased Estimation: Ridge Regression](notes/05-04-biased-estimation-ridge-regression.html) <span style="color: #ff2d21; font-size:13px;"> [<i>Updated 2025-10-24</i>]</span>
- **Model Selection**
  + [Model Selection Worksheet](worksheets/02-model-selection.html)
  + [Automated Methods for Model Selection](notes/06-01-automated-methods.html)
  + [Cross-Validation Methods for Model Selection](notes/06-02-cross-validation.html)
  + [Cross-Validation Methods: Ridge Regression](notes/06-03-cv-ridge-regression.html) | [Script file](scripts/06-03-cv-ridge-regression.R) <span style="color: #ff2d21; font-size:13px;"> [<i>Updated 2025-12-03</i>]</span>
</nav>


<br />


<!-- ## Worksheets -->

<!-- <nav aria-label="worksheets"> -->
<!-- - [Introduction to Matrix Algebra](worksheets/01-introduction-to-matrix-algebra.html) -->

<!-- </nav> -->
